ARG VERSION=latest

FROM prom/prometheus:${VERSION}

# Copy the prom.yml configuration file to the container
COPY prom.yml /etc/prometheus/prom.yml
COPY web-config.yml /etc/prometheus/web-config.yml

# Command to run Prometheus
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus", "--web.config.file=/etc/prometheus/web-config.yml"]
