ARG VERSION=latest

FROM prom/prometheus:${VERSION}

# Copy the prom.yml configuration file to the container
COPY prom.yml /etc/prometheus/prom.yml

# Command to run Prometheus
CMD ["--config.file=/prometheus/prom.yml", "--storage.tsdb.path=/prometheus" "--web.config.file=/prometheus/web-config.yml"]
